import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { DM_Sans } from "next/font/google";
import "./globals.css";
import Providers from "./providers";

const dm_sans = DM_Sans({
  subsets:["latin"],
  display:"swap",
  variable:"--font-dm-sans"
})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${dm_sans.className}`}
      >
        <Providers>

        {children}
        </Providers>
      </body>
    </html>
  );
}
